# TCL File Generated by Component Editor 18.0
# Sat May 04 21:50:34 EDT 2019
# DO NOT MODIFY


# 
# std_logic_generator "std_logic_generator" v1.1
# Austin Esquirell 2019.05.04.21:50:34
# Generates a constant std_logic conduit signal - Used on "high" to enable random number generator
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module std_logic_generator
# 
set_module_property DESCRIPTION "Generates a constant std_logic conduit signal - Used on \"high\" to enable random number generator"
set_module_property NAME std_logic_generator
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Esquirel_IP
set_module_property AUTHOR "Austin Esquirell"
set_module_property DISPLAY_NAME std_logic_generator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL std_logic_generator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file std_logic_generator.vhd VHDL PATH std_logic_generator.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter std_logic_output_value STD_LOGIC 1
set_parameter_property std_logic_output_value DEFAULT_VALUE 1
set_parameter_property std_logic_output_value DISPLAY_NAME std_logic_output_value
set_parameter_property std_logic_output_value TYPE STD_LOGIC
set_parameter_property std_logic_output_value UNITS None
set_parameter_property std_logic_output_value ALLOWED_RANGES 0:1
set_parameter_property std_logic_output_value HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point std_logic_output
# 
add_interface std_logic_output conduit end
set_interface_property std_logic_output associatedClock clock_sink
set_interface_property std_logic_output associatedReset reset_sink
set_interface_property std_logic_output ENABLED true
set_interface_property std_logic_output EXPORT_OF ""
set_interface_property std_logic_output PORT_NAME_MAP ""
set_interface_property std_logic_output CMSIS_SVD_VARIABLES ""
set_interface_property std_logic_output SVD_ADDRESS_GROUP ""

add_interface_port std_logic_output std_logic_output_value enable Output 1

